service: lambda-typescript-jest
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: endpoint
          method: post

plugins:
  - serverless-offline
  - serverless-plugin-typescript
